language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      # Required by sibyl
      - jq
      # ShellCheck linter
      - shellcheck
      # Required by kcov
      - binutils-dev
      - libcurl4-openssl-dev
      - zlib1g-dev
      - libdw-dev
      - libiberty-dev
      - cmake

script:
  - make setup
  - make build
  - make lint
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push stencila/sibyl;
      docker push stencila/alpha;
    fi
